'use client'

import { useEffect, useState } from 'react'
import { ArrowRight, Check, ChevronDown, CircleCheck, HeartHandshake, Home, Menu, Pause, Play, Sparkles, Users, X, BriefcaseBusiness, Building2, HandHeart, ClipboardList, Phone, Mail, MapPin, Stethoscope } from 'lucide-react'

const nav = ['About', 'Services', 'Careers', 'Government & Non-profit']
const services = [
  ['Healthcare Services', 'Practical, respectful care and everyday support that promotes dignity, safety and independence.', HeartHandshake],
  ['Residential Housekeeping', 'Reliable cleaning, laundry and home assistance that helps people feel comfortable where they live.', Home],
  ['Commercial Housekeeping', 'Professional cleaning solutions for workplaces, facilities and organisations across Canada.', Sparkles],
  ['Community Support', 'Companionship, respite and practical programs that connect people to the support they need.', Users],
  ['Partnerships & Contracts', 'Flexible staffing and contracted services for government, non-profits, facilities and businesses.', BriefcaseBusiness],
  ['Personal Care & Respite', 'Person-centred support for seniors, people with disabilities and families who need a helping hand.', HandHeart],
  ['HCA & Caregiver Services', 'Qualified home support workers and caregivers providing dependable, respectful assistance in daily life.', Stethoscope],
  ['Companion Care', 'Warm companionship, social connection and practical help that supports confidence at home and in the community.', HeartHandshake],
  ['Dementia Support', 'Calm, consistent support for people living with dementia and the families who care for them.', Users],
  ['Post-Hospital Support', 'A thoughtful transition home with short-term help, routines and practical recovery support.', ClipboardList],
  ['Meal, Transportation & Errands', 'Practical assistance with meals, appointments, transportation and everyday tasks.', MapPin],
  ['Facility & Workforce Support', 'Dependable people and coordinated services for care environments and community organisations.', Building2],
]
const steps = [['01', 'Tell Us What You Need', 'Submit a service request or contact our team.'], ['02', 'We Understand Your Needs', 'We review the request and determine the right approach.'], ['03', 'We Coordinate Support', 'We organise the right people, schedule and resources.'], ['04', 'Support Begins', 'Receive dependable service with ongoing communication.']]
const heroPanels = [
  ['care', '/lifeline-care.png', 'Care & support', 'Caregiver supporting an older adult'],
  ['home', '/lifeline-home.png', 'Home services', 'Home support in a bright living space'],
  ['cleaning', '/lifeline-cleaning.png', 'Professional cleaning', 'Cleaner working in a commercial environment'],
  ['workforce', '/lifeline-team.png', 'Workforce solutions', 'Lifeline professionals at work'],
  ['community', '/lifeline-community.png', 'Community programs', 'People gathering in community'],
]

function Logo() { return <a href="#home" className="logo" aria-label="Lifeline Community Care and Home Services Co-operative home"><img src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lifeline-tQrRZ8Fyw0JQEnaExbawbAHoJbXoV8.png" alt="Lifeline Community Care and Home Services Co-operative" style={{ width: '156px', height: 'auto' }} /></a> }
function Button({ children, light = false, href = '#contact' }: { children: React.ReactNode, light?: boolean, href?: string }) { return <a href={href} className={`button ${light ? 'button-light' : ''}`}>{children}<ArrowRight size={16} /></a> }

export default function Page() {
  const [open, setOpen] = useState(false)
  const [activePanel, setActivePanel] = useState(0)
  const [isPaused, setIsPaused] = useState(false)

  useEffect(() => {
    if (isPaused) return
    const timer = window.setInterval(() => setActivePanel((current) => (current + 1) % heroPanels.length), 5000)
    return () => window.clearInterval(timer)
  }, [isPaused])

  return <main id="home">
    <header className="nav-wrap"><nav className="nav container"><Logo /><div className="desktop-nav"><a href="#home">Home</a>{nav.map(item => <a href={`#${item.toLowerCase().replaceAll(' ', '-')}`} key={item}>{item}</a>)}</div><div className="nav-actions"><a className="quote" href="#contact">Get a Quote</a><Button href="#contact">Request Services</Button></div><button className="menu-btn" aria-label={open ? 'Close menu' : 'Open menu'} onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></nav>{open && <div className="mobile-menu"><a href="#home" onClick={() => setOpen(false)}>Home</a>{nav.map(item => <a key={item} href={`#${item.toLowerCase().replaceAll(' ', '-')}`} onClick={() => setOpen(false)}>{item}</a>)}<Button href="#contact">Request Services</Button></div>}</header>

    <section className="hero-slider" aria-labelledby="hero-title">
      <div className="hero-slider-track" style={{ transform: `translateX(-${activePanel * 100}%)` }}>
        {heroPanels.map(([key, image, label, alt], index) => <article className={`hero-slide hero-slide-${key}`} key={key}>
          <img src={image} alt={alt} />
          <div className="hero-slide-shade" />
          <div className="container hero-slide-content"><p className="eyebrow eyebrow-light">SERVING COMMUNITIES ACROSS CANADA</p><p className="hero-slide-kicker">0{index + 1} / 05 &nbsp; {label}</p><h1 id={index === 0 ? 'hero-title' : undefined}>{key === 'care' ? <>Support for real life.<br /><em>In every space.</em></> : key === 'home' ? <>A better day<br /><em>starts at home.</em></> : key === 'cleaning' ? <>Spaces that feel<br /><em>ready for life.</em></> : key === 'workforce' ? <>The right people<br /><em>make it possible.</em></> : <>Stronger communities<br /><em>start together.</em></> }</h1><p className="hero-slide-description">{key === 'care' ? 'Care, home support, cleaning and community services brought together from one trusted local team.' : key === 'home' ? 'Practical home care and everyday assistance that helps people live with comfort, confidence and independence.' : key === 'cleaning' ? 'Dependable residential, commercial and institutional cleaning for the places people live, work and gather.' : key === 'workforce' ? 'Flexible staffing and contract support for facilities, organisations and care environments.' : 'Community programs and partnerships that connect people to practical support across Canada.'}</p><div className="hero-buttons"><Button light>{label === 'Care & support' ? 'Request a Service' : `Explore ${label}`}</Button><a className="text-link text-link-light" href="#services">View all services <ArrowRight size={16} /></a></div><div className="hero-location"><MapPin size={14} /><span>Victoria · Vancouver Island · British Columbia</span><i /> <span>Local, dependable service</span></div></div>
        </article>)}
      </div>
      <div className="container hero-slider-controls"><div className="hero-slider-dots" role="tablist" aria-label="Lifeline services">{heroPanels.map(([key, , label], index) => <button key={key} className={index === activePanel ? 'active' : ''} onClick={() => setActivePanel(index)} aria-label={`Show ${label}`} aria-selected={index === activePanel} role="tab"><span>0{index + 1}</span><i /><b>{label}</b></button>)}<button className="hero-pause" onClick={() => setIsPaused((paused) => !paused)} aria-label={isPaused ? 'Resume slider' : 'Pause slider'}>{isPaused ? <Play size={13} /> : <Pause size={13} />}</button></div><a href="#intro" className="hero-scroll">Explore Lifeline <ChevronDown size={16} /></a></div>
    </section>

    <section className="intro-strip" id="intro"><div className="container intro-grid"><div><p className="eyebrow">ONE ORGANISATION. MANY WAYS TO HELP.</p><h2>Support that goes<br />beyond a service.</h2></div><div><p className="intro-text">From individuals and families to facilities, businesses, non-profits and community organizations, Lifeline provides practical support across Canada, where it matters most.</p><div className="mini-links"><span>01 &nbsp; Home support</span><span>02 &nbsp; Care services</span><span>03 &nbsp; Workforce support</span><span>04 &nbsp; Community services</span></div></div></div></section>

    <section className="section container" id="services"><div className="section-heading"><div><p className="eyebrow">WHAT WE DO</p><h2>Services built around<br /><em>real needs.</em></h2></div><p>Flexible support for individuals, families, organisations and communities.</p></div><div className="services-grid">{services.map(([title, desc, Icon], i) => <article className={`service-card ${i === 0 ? 'featured-service' : ''}`} key={title}><div className="service-top"><span className="service-icon"><Icon size={22} /></span><span className="service-number">0{i + 1}</span></div><h3>{title}</h3><p>{desc}</p><a href="#contact">Explore service <ArrowRight size={15} /></a></article>)}</div></section>

    <section className="care-feature container" id="about"><div className="care-image"><img src="/lifeline-home.png" alt="Home support worker assisting a woman in a bright living room" /><div className="round-badge">CARE<br />WITH<br /><span>respect</span></div></div><div className="care-copy"><p className="eyebrow">PERSON-CENTRED CARE</p><h2>Support that respects <em>the individual.</em></h2><p>Every person has different routines, preferences and needs. Lifeline focuses on practical, respectful support that helps people remain comfortable, connected and as independent as possible.</p><ul>{['Personalised support', 'Dignity and respect', 'Family-focused communication', 'Flexible care options'].map(x => <li key={x}><CircleCheck size={19} />{x}</li>)}</ul><a className="text-link" href="#services">Learn about our care services <ArrowRight size={16} /></a></div></section>

    <section className="org-section" id="government-&-nonprofit"><div className="container"><div className="org-heading"><div><p className="eyebrow eyebrow-light">FOR ORGANISATIONS</p><h2>More than<br /><em>home care.</em></h2></div><p>Lifeline also works with organizations that need dependable people, cleaning services, community support and flexible workforce solutions across Canada.</p></div><div className="org-grid">{[['Facilities','Staffing and support for care and residential environments.',Building2],['Businesses','Professional commercial and workplace services.',BriefcaseBusiness],['Government','Community programmes and contracted support.',ClipboardList],['Nonprofits & Community','Practical services that strengthen community initiatives.',Users]].map(([t,d,I]) => <a className="org-card" href="#contact" key={t}><I /><span><b>{t}</b><small>{d}</small></span><ArrowRight /></a>)}</div><Button light href="#contact">Government & Non-profit Services</Button></div></section>

    <section className="why-section" id="cooperative"><div className="container"><div className="section-heading"><div><p className="eyebrow">THE LIFELINE DIFFERENCE</p><h2>Why families and<br /><em>organisations choose us.</em></h2></div></div><div className="why-grid">{[['01','People First','Services designed around people, not just processes.'],['02','Flexible Support','Services that adapt to changing needs and circumstances.'],['03','Professional Approach','Structured service delivery with clear communication and accountability.'],['04','Community Focus','Practical support that helps people, families and communities thrive.']].map(([n,t,d]) => <div className="why-item" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>

    <section className="process-section"><div className="container process-wrap"><div className="process-intro"><p className="eyebrow">A SIMPLE START</p><h2>How it <em>works.</em></h2><p>Good support begins with listening. We make the next step clear and straightforward.</p><Button href="#contact">Request Services</Button></div><div className="steps">{steps.map(([n,t,d]) => <div className="step" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>

        <section className="careers container" id="careers"><div className="career-image"><img src="/lifeline-team.png" alt="Diverse professional support team standing together" /></div><div className="career-copy"><p className="eyebrow">JOIN THE TEAM</p><h2>Build meaningful<br /><em>work with Lifeline.</em></h2><p>We are creating opportunities for people who want to make a practical difference in the lives of individuals, families and communities.</p><div><Button href="#contact">View Careers</Button><a className="text-link" href="#contact">Apply now <ArrowRight size={16} /></a></div></div></section>

    <section className="intake-section container" id="request-care"><div className="intake-copy"><p className="eyebrow">START WITH A CONVERSATION</p><h2>Request care, home services or a <em>partnership.</em></h2><p>Tell us what you need and our team will follow up with the right next step. This form is ready to connect to the secure client intake workflow.</p><div className="intake-links"><a href="#careers"><BriefcaseBusiness size={17}/>Apply as a worker or HCA <ArrowRight size={15}/></a><a href="mailto:hello@lifelinecooperative.org"><Mail size={17}/>Contact the Lifeline team <ArrowRight size={15}/></a></div></div><form className="intake-form" onSubmit={(event) => event.preventDefault()}><label>What can we help with?<select defaultValue=""><option value="" disabled>Select a service</option><option>Home care and personal support</option><option>Residential housekeeping</option><option>Commercial housekeeping</option><option>Community or partnership support</option></select></label><label>Your email<input type="email" placeholder="you@example.com" required /></label><label>How can we support you?<textarea placeholder="Share a few details..." rows={3} /></label><button className="admin-primary" type="submit">Submit request <ArrowRight size={16}/></button><small>We&apos;ll use your information only to respond to this request. Privacy Policy · Terms of Use</small></form></section>

    <section className="final-cta" id="contact"><div className="container final-inner"><div><p className="eyebrow eyebrow-light">LET'S TALK</p><h2>Let&apos;s find the<br /><em>right support</em> for you.</h2><p>Whether you need care at home, support for a loved one, cleaning services, workforce support or a community partnership, we&apos;re ready to listen.</p></div><div className="final-action"><Button light>Request Services</Button><a className="outline-button" href="mailto:hello@lifelinecooperative.org">Contact Lifeline <ArrowRight size={16} /></a><div className="contact-details"><span><Phone size={15} /> (000) 000-0000</span><span><Mail size={15} /> hello@lifelinecooperative.org</span></div></div></div></section>

    <footer><div className="container footer-grid"><div><Logo /><p className="footer-about">Care, support and practical services for stronger people and communities.</p></div><div><h4>Company</h4><a href="#about">About</a><a href="#services">Services</a><a href="#about">Our approach</a><a href="#careers">Careers</a><a href="#contact">Contact</a></div><div><h4>Services</h4><a href="#services">Home Care</a><a href="#services">Senior & Disability Care</a><a href="#services">Respite</a><a href="#services">Housekeeping</a><a href="#services">Staffing</a></div><div><h4>Get started</h4><a href="#contact">Request Services</a><a href="#contact">Request a Quote</a><a href="#careers">Careers</a><a href="#contact">Government & Nonprofit</a></div></div><div className="container footer-bottom"><span>© Lifeline Community Care & Home Services · Canada</span><span>Privacy Policy &nbsp;&nbsp; Terms of Use &nbsp;&nbsp; Accessibility</span></div></footer><a className="floating-contact" href="#contact" aria-label="Contact Lifeline"><Phone size={19} /></a>
  </main>
}
